### ISSUE TITLE
A suggestion to add SLOPE_FUZZ as a strategy item

### ISSUE THREAD

**Issue by jimmymasaru** [be5invis/sfdhanautohint#1]
As title.
根据我的理解，SLOPE_FUZZ是水平笔划斜率的阈值。
但对于有喇叭口的黑体，默认的0.04不太够，可能要0.15到0.2比较合适。
建议将其作为一个策略项，可以在命令行参数上设定。

修改前
<img width="589" alt="img_0941" src="https://cloud.githubusercontent.com/assets/12769660/8556728/0ce69226-254d-11e5-9b8d-d8e516302a58.PNG">
修改后（0.14，我要是没记错的话）
<img width="585" alt="img_0943" src="https://cloud.githubusercontent.com/assets/12769660/8556739/1e21266e-254d-11e5-91d7-588c5440a176.PNG">
Strategy
--MOST_COMMON_STEM_WIDTH 100 --MIN_STEM_WIDTH 45 --MAX_STEM_WIDTH 135 --gears [[0,1,1],[18,2,1],[24,3,2]]
不过18ppem才到2像素的确有点晚。

**Comment by be5invis** [comment]
Github does not send me email about new issues......

I will replace the stemfinding algorithm entirely in order to produce better stemfinding, avoiding "stem break" around decorative features, like the example you provided.

**Comment by be5invis** [comment]
Added in 0.2.0. Closed.
