### ISSUE TITLE
At ~20ppem, strokes often become too high

### ISSUE THREAD

**Issue by farteryhr** [be5invis/sfdhanautohint#7]
从13ppem起就是这样，最明显的是示例的那个“上”。流游上面的点到18ppem才展开成2像素，远的元裸横贴顶也是到18ppem……
所以要不要加一点平衡参数，比如某一块内对齐像素后相对原位置的平均偏移？

再另还是求扁像素【既然都跟stock对比了嘛

补充
就不开新的了
https://www.microsoft.com/en-us/Typography/vtt.aspx 你怎么看。

**Comment by be5invis** [comment]
The strategy has been changed in 0.2.0, which prevents intensive stroke expansion.
Closed.
